# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['message_flight.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'winsdk',
        'win32com.client',
        'pythoncom',
        'message_flight',
        'message_flight.autostart',
        'message_flight.demo_notifications',
        'message_flight.notification_worker',
        'message_flight.plane_banner',
        'message_flight.flight_widget',
        'message_flight.tray_app',
        'message_flight.tts',
        'message_flight.tts_manager',
        'message_flight.config',
        'message_flight.settings_dialog',
        'message_flight.plane_presets',
        'message_flight.plane_presets.airplane',
        'message_flight.plane_presets.rocket',
        'message_flight.plane_presets.ufo',
        'message_flight.plane_presets.bird',
        'message_flight.plane_presets.sleigh',
        'message_flight.plane_presets.duck',
        'message_flight.plane_presets.rainbow_rocket',
        'message_flight.plane_presets.gold_ufo',
        'message_flight.plane_presets.pixel_bird',
        'message_flight.preset_editor',
        'message_flight.achievements',
        'message_flight.achievement_engine',
        'message_flight.toast',
        'message_flight.collection_tab',
        'pygame',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MessageFlight',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
